scalar Date

type User {
  id: String!,
  name: String!,
  email: String!,
  username: String!,
  avatar: String,
  avatar_url: String,
  enabled: Boolean!,
  created_at: Date!,
  updated_at: Date!,
}

type Query {
  listAllUsers: [User]
}

input CreateUserInput {
  name: String!,
  email: String!,
  password: String!,
  creator_id: String,
  role: String,
}

type Mutation {
  createUser(input: CreateUserInput!): User
}
